### ISSUE TITLE
Set up a CI build (eg. travis)

### ISSUE THREAD

**Issue by 1ace** [KhronosGroup/Vulkan-ExtensionLayer#10]
Happy to set it up code-wise, but someone in the `KhronosGroup` group will need to enable it.

**Comment by djdeath** [comment]
If you can contribute a PR that would be amazing :)

**Comment by Khronoswebmaster** [comment]
You only need to add the travis build file and trigger a build. It should automatically connect you to Travis-ci.com. If this doesn't happen, let me know.

**Comment by djdeath** [comment]
Odd... Now the CI doesn't show up anymore.

**Comment by 1ace** [comment]
I think everything's working, it was just that your `.travis.yml` change resulted in an invalid file.

Closing again :+1:
