### ISSUE TITLE
How Can I ship my application with Vulkan-ExtensionLayer

### ISSUE THREAD

**Issue by maxxnino** [KhronosGroup/Vulkan-ExtensionLayer#102]
My potato gpu don't have `khr_synchronization_2` support by the driver. So I have to use `Vulkan-ExtensionLayer`. Enable by forcing it with `VK_INSTANCE_LAYERS` environment variable, and use it from application. It's work fine on my machine. But how can I ship it to different pc with no  `khr_synchronization_2` support by the driver.

**Comment by maxxnino** [comment]
The `"VK_LAYER_KHRONOS_synchronization2"` really did the trick. Thank you for an extensive list of informations. I just wish the loader can scan at the root application for required the layer .json file and .so/.dll. That would make thing much simpler

**Comment by jeremyg-lunarg** [comment]
> The `"VK_LAYER_KHRONOS_synchronization2"` really did the trick. Thank you for an extensive list of informations.


>  I just wish the loader can scan at the root application for required the layer .json file and .so/.dll. That would make thing much simpler
