### ISSUE TITLE
How to compile for Android on Windows?

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/Vulkan-ExtensionLayer#135]
How do I compile these layers for Android if I'm running on Windows?

The [build instructions](https://github.com/KhronosGroup/Vulkan-ExtensionLayer/blob/master/BUILD.md) say to run a script `build-android/build-all.sh`, which is not a Windows script

I also tried running `build-android/update_external_sources_android.bat`, since it was a Windows batch file, but I got the error `'py' is not recognized as an internal or external command, operable program or batch file.` I'm not even sure what `py` is - some alias for `python`?

Is it possible to compile for Android from a Windows?

**Comment by jeremyg-lunarg** [comment]
py.exe is the windows launcher for python see: https://docs.python.org/3/using/windows.html

Once you have that you should be able to build with these instructions from[ Vulkan-ValidationLayers' BUILD.md](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md#building-on-android)

```
cd build-android
update_external_sources_android.bat
ndk-build
```

ndk-build.cmd must be in a directory in %PATH% for this to work, it looks like its location is different in recent versions of the SDK. I'll update the build docs to explain this better, but in general the build system is largely the same in these 2 projects but Vulkan-ValidationLayers is more active so often has more clues about how to do things.
