### ISSUE TITLE
Building libVkLayer_khronos_synchronization2.so for Android x86_64

### ISSUE THREAD

**Issue by manvis** [KhronosGroup/Vulkan-ExtensionLayer#171]
Hello, I wanted to use the synchronization layer on the Android. I'm currently testing my code on the x86_64 emulator because of the much better performance.

I've followed the build instructions for Android (I'm on Linux) and I ended up with two folders containing the built .so files

- libs/arm64-v8a
- libs/armeabi-v7a

How do I get the x86_64 version of the .so built for Android?

Thanks!

**Comment by jeremyg-lunarg** [comment]
You'd need to change this line:
`
build-android/jni/Application.mk:APP_ABI := armeabi-v7a arm64-v8a
`

See https://developer.android.com/ndk/guides/application_mk

We took it out by default because we didn't think it was ever being used.

**Comment by manvis** [comment]
So, that's what I needed to change. My lack of Android build system knowledge is showing :smile:.

Thank you. I just got it built. Disabling x86_64 by default makes sense. I don't think that there are many (any?) x86_64 devices in the wild and not having it enabled by default saves build time.
