### ISSUE TITLE
Missing uninstall target: "make: *** No rule to make target 'uninstall'.  Stop."

### ISSUE THREAD

**Issue by codecnotsupported** [KhronosGroup/Vulkan-ExtensionLayer#179]
Followed the guide:
https://github.com/KhronosGroup/Vulkan-ExtensionLayer/blob/main/BUILD.md#installed-files
I used a `Release` build instead of `Debug` build.
```
sudo make uninstall
make: *** No rule to make target 'uninstall'.  Stop.
```

`Install` works fine.

**Comment by juan-lunarg** [comment]
The documentation is outdated. Apologies for the confusion.

**Comment by juan-lunarg** [comment]
If you need to uninstall this may be helpful reference:
https://stackoverflow.com/questions/1439950/whats-the-opposite-of-make-install-i-e-how-do-you-uninstall-a-library-in-li

**Comment by codecnotsupported** [comment]
> If you need to uninstall this may be helpful reference: https://stackoverflow.com/questions/1439950/whats-the-opposite-of-make-install-i-e-how-do-you-uninstall-a-library-in-li

Thanks,
Running `cat install_manifest.txt | xargs echo sudo rm | sh` in the build directory works fine.
