### ISSUE TITLE
install target ships incorrect files

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ExtensionLayer#183]
The **Windows** `install` target currently installs various `.lib` files.  It should not, as these are not shipped by the SDK.

The SDK is also planning on not shipping 32-bit artifacts for the `VK_LAYER_KHRONOS_shader_object` (though it will continue to ship 32-bit `VK_LAYER_KHRONOS_synchronization2` artifacts).  So the 32-bit `install` target should not ship `Bin\VkLayer_khronos_shader_object.dll`, `Bin\VkLayer_khronos_shader_object.json`, or `,Bin\VkLayer_khronos_shader_object.pdb`.

**Comment by juan-lunarg** [comment]
duplicate:
https://github.com/KhronosGroup/Vulkan-ExtensionLayer/issues/182

Thanks for the nice write up though. I copied it over.
