### ISSUE TITLE
Cannot find source file VkLayer_khronos_timeline_semaphore.def

### ISSUE THREAD

**Issue by zisner** [KhronosGroup/Vulkan-ExtensionLayer#2]
Hello,

I'm very excited that timeline semaphores have been added to Vulkan 1.2! Since the new SDK is not yet released, I was hoping to try and get this working in our application using 1.1 versions.

I'm currently on Windows 10 using the VulkanSDK 1.1.121.2 and running into an issue while building with cmake. I'm able to finish configuring, but then it seems to be unable to find `VkLayer_khronos_timeline_semaphore.def`.  

Here's the error message I'm getting:

```
CMake Error at layers/CMakeLists.txt:64 (add_library):
  Cannot find source file:

    VkLayer_khronos_timeline_semaphore.def

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  layers/CMakeLists.txt:114 (AddVkLayer)


CMake Error at layers/CMakeLists.txt:64 (add_library):
  No SOURCES given to target: VkLayer_khronos_timeline_semaphore
Call Stack (most recent call first):
  layers/CMakeLists.txt:114 (AddVkLayer)


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Any help would be greatly appreciated. Thanks a bunch!

**Comment by djdeath** [comment]
Sorry I missed the notifications on the repo. PR up to fix this.
