### ISSUE TITLE
Bad behaviour of captured `vkEnumerateDeviceExtensionProperties`

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-ExtensionLayer#289]
In every extension layer in this repository captured `vkEnumerateDeviceExtensionProperties` advertise their extensions if `pLayerName == NULL`, but the spec states:

> When pLayerName parameter is NULL, only extensions provided by the Vulkan implementation or by implicitly enabled layers are returned. When pLayerName is the name of a layer, the device extensions provided by that layer are returned.

**Comment by jeremyg-lunarg** [comment]
@charles-lunarg ISTR we discussed this at some point in the last few months and decided that these layers were doing what they needed. But I cannot find where. Do you remember?

**Comment by qbojj** [comment]
This issue was more of "is it intended behaviour on not" rather then "found an error", so if it is by-design that's fine with me.

**Comment by charles-lunarg** [comment]
The other discussion can be found here: https://github.com/KhronosGroup/Vulkan-Docs/issues/2033
