### ISSUE TITLE
The readme could use some expansion

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/Vulkan-ExtensionLayer#34]
For instance

- Which features are implemented
- How they are implemented

**Comment by sfricke-samsung** [comment]
I agree it would be nice to have a "summary" of the design of each layer/extension with just more general information

Happy to write this up in an upcoming PR I have

**Comment by expipiplus1** [comment]
Thanks!

**Comment by jeremyg-lunarg** [comment]
Closing. There's detailed docs for the sync2 layer, any new extensions supported should follow this model. Timeline semaphore is what it is for the time being since most drivers support the extension at this point.
