### ISSUE TITLE
[Shader Object] Incorrect structure type reported in pNext chain of device create info

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-ExtensionLayer#344]
Originally reported in [LunarG/VulkanTools](https://github.com/LunarG/VulkanTools/issues/1882)

The validation layers see a VK_STRUCTURE_TYPE_PRIVATE_DATA_SLOT_CREATE_INFO. This happens with shader object layer on and the extension enabled. With the extension disabled and the layer enabled, it does not happen.

I cannot tell if this is a bug with the validation layers or the shader object layer. But it definitely seems like a bug, as I could not typo in a create info structure.

**Comment by juan-lunarg** [comment]
This might be a good case for enabling the validation layers during extension layer testing all things considered.

**Comment by ziga-lunarg** [comment]
This has already been fixed by #313
