### ISSUE TITLE
VkPhysicalDeviceTimelineSemaphoreFeatures contains false even when this layer is enabled

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/Vulkan-ExtensionLayer#37]
Hi,

I'm trying to use this layer with [a small program](https://github.com/expipiplus1/vulkan/blob/79aaa3b3b029d173a3df00b3096e7d2cde8e5509/examples/timeline-semaphore/Main.hs) which tests timeline semaphores.

I can clearly see in the code that `VkPhysicalDeviceTimelineSemaphoreFeatures` [should contain true](https://github.com/KhronosGroup/Vulkan-ExtensionLayer/blob/master/layers/timeline_semaphore.c#L2017), so I'm not sure what's going on here. I'm sure the layer is working because if I ignore this being false and continue execution the program only works when I request this layer. 

I've attached the output of api_dump below, putting `>>>` on the line where the layer is requested, and the line where the feature is declared unsupported.

```
❯ VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump timeline-semaphore-example
Up to date
Thread 0, Frame 0:
vkCreateInstance(pCreateInfo, pAllocator, pInstance) returns VkResult VK_SUCCESS (0):
    pCreateInfo:                    const VkInstanceCreateInfo* = 0x7ffd20cc26a0:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO (1)
        pNext:                          const void* = NULL
        flags:                          VkInstanceCreateFlags = 0
        pApplicationInfo:               const VkApplicationInfo* = 0x420100c180:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_APPLICATION_INFO (0)
            pNext:                          const void* = NULL
            pApplicationName:               const char* = NULL
            applicationVersion:             uint32_t = 0
            pEngineName:                    const char* = NULL
            engineVersion:                  uint32_t = 0
            apiVersion:                     uint32_t = 4194304
        enabledLayerCount:              uint32_t = 1
        ppEnabledLayerNames:            const char* const* = 0x420100c1c0
>>>         ppEnabledLayerNames[0]:         const char* const = "VK_LAYER_KHRONOS_timeline_semaphore"
        enabledExtensionCount:          uint32_t = 1
        ppEnabledExtensionNames:        const char* const* = 0x420100c220
            ppEnabledExtensionNames[0]:     const char* const = "VK_KHR_get_physical_device_properties2"
    pAllocator:                     const VkAllocationCallbacks* = NULL
    pInstance:                      VkInstance* = 0x17406f0

<snip>

Thread 0, Frame 0:
vkGetPhysicalDeviceFeatures2KHR(physicalDevice, pFeatures) returns void:
    physicalDevice:                 VkPhysicalDevice = 0x17c5c00
    pFeatures:                      VkPhysicalDeviceFeatures2* = 0x175de40:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2 (1000059000)
        pNext:                          VkPhysicalDeviceTimelineSemaphoreFeatures = 0x175df40:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_FEATURES (1000207000)
            pNext:                          void* = NULL
>>>         timelineSemaphore:              VkBool32 = 0 
        features:                       VkPhysicalDeviceFeatures = 0x175de50:
            robustBufferAccess:             VkBool32 = 1
            <snip>

<snip>
```

**Comment by djdeath** [comment]
You need to enable the layer with `VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_timeline_semaphore`

**Comment by expipiplus1** [comment]
@djdeath I'm already passing it in `ppEnabledLayerNames` at instance creation time. Having it in `VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump:VK_LAYER_KHRONOS_timeline_semaphore`  also makes no difference.

**Comment by djdeath** [comment]
Okay, can you verify the loader is actually loading it?

It should be in the traces with this variable : `VK_LOADER_DEBUG=all`

**Comment by djdeath** [comment]
Ah, I think I see the problem, we've registered the new name for the function of the Vulkan 1.2 spec where `vkGetPhysicalDeviceFeatures2KHR` has become core as `vkGetPhysicalDeviceFeatures2` so we're missing this symbol name.

**Comment by expipiplus1** [comment]
> Okay, can you verify the loader is actually loading it?
> 
> It should be in the traces with this variable : `VK_LOADER_DEBUG=all`

Ah yes, I did do this but forgot to add it to the issue!


> Ah, I think I see the problem, we've registered the new name for the function of the Vulkan 1.2 spec where `vkGetPhysicalDeviceFeatures2KHR` has become core as `vkGetPhysicalDeviceFeatures2` so we're missing this symbol name.

Makes sense! Glad to know what was causing this

**Comment by djdeath** [comment]
Would you mind trying : https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/38

**Comment by expipiplus1** [comment]
Thanks for such a quick resolution!
