### ISSUE TITLE
vk cts failed "dEQP-VK.api.object_management.alloc_callback_fail.instance"

### ISSUE THREAD

**Issue by JaxLinAMD** [KhronosGroup/Vulkan-ExtensionLayer#42]
error msg:
Fail (Invalid allocation callback)

Test case 'dEQP-VK.api.object_management.alloc_callback_fail.device'..
double free or corruption (!prev)

**Comment by djdeath** [comment]
Is this the same as https://github.com/KhronosGroup/Vulkan-ExtensionLayer/issues/27 ?

Seems to be a loader bug.

**Comment by JaxLinAMD** [comment]
yes! can it be workaround in this layer? it seems #29 can partially workaround this issue?

**Comment by djdeath** [comment]
From what I remember there was no way to workaround this.
